# List of Transformations used in ambf_tf_plugin
# Author: Hisashi Ishida (hishida3@jhu.edu)

transformations:
  - TF world-atracsys_drill_marker
  - TF marker_body-drill_tip
  - TF pointer_tip-drill_body

TF world-atracsys_drill_marker: # Move drill with atracsys measurements
  parent: World
  child: marker
  type: ROS
  rostopic name: /atracsys/pointer_tool/measured_cp

TF marker_body-drill_tip: 
  parent: marker
  child: pointer_tip 
  type: FIXED
  transformation: # pointer tool - pivot calibration
    position: {x: 0.0122844, y: -0.131931, z: -0.031379}
    Mean calibration error: 0.000291994
    orientation: { r: 0.0, p: 0.0, y: 0.0 }

## This sets the drill body orientation with respect to the drill reference body.
# This value came from doing two pivot calibrations with shafts of different lenghts
# This enables you to calculate the drill's body angle with respect to the ref body.
TF pointer_tip-drill_body:
  parent: pointer_tip
  child: drill_body_4mm
  type: FIXED
  transformation:
    position: { x: 0.0, y: 0.0, z: 0.0 }
    orientation: { r: 0.0, p: 0.0, y: 2.84 } # For handheld drill. This should be around 117.4 degrees acording to ADF file
