
output_dir: /home/juan95/research/discovery_grant/saint_2026/experiments/experiment_xx

segmentation_path: /home/juan95/research/discovery_grant/saint_tools/saint_automation_tools/data/sample_phantom/P01_05_real_seg.seg.nrrd
fiducials_path: /home/juan95/research/discovery_grant/saint_tools/saint_automation_tools/data/sample_phantom/P01_05_pre.mrk.json

copy_input_files: true 

script_paths:
  nrrd_to_adf_script: /home/juan95/research/discovery_grant/saint_tools/nrrd_to_adf_hisashi/nrrd_to_adf.py
  update_seg_nrrd_script: /home/juan95/research/discovery_grant/saint_tools/nrrd_to_adf_hisashi/update_seg_nrrd_data_from_pngs.py
  create_saint_config_script: /home/juan95/research/discovery_grant/saint_tools/saint_automation_tools/src/config_creation/create_saint_config.py

output_dir_structure:
  phantom_dir: phantom
  config_dir: config
  input_backup_dir: input_backup 
  ros_bag_dir: ros_bag

saint_config:
  saint_root: /home/juan95/research/discovery_grant/volumetric_drilling
  drill_size: 4
  drill_marker_namespace: /atracsys/drill_marker
  pointer_marker_namespace: /atracsys/pointer_tool

