
output_dir: /Users/juan95/research/saint_project/saint-utils/output/experiment_xx
segmentation_path: /Users/juan95/research/saint_project/saint-utils/data/phantom01_05/P01_05_real_seg.seg.nrrd
fiducials_path: /Users/juan95/research/saint_project/saint-utils/data/phantom01_05/P01_05_pre.mrk.json

copy_input_files: true 

script_paths:
  nrrd_to_adf_script: /Users/juan95/research/saint_project/nrrd_to_adf/nrrd_to_adf.py
  create_saint_config_script: /Users/juan95/research/saint_project/saint-utils/src/config_creation/create_saint_config.py

output_dir_structure:
  phantom_dir: phantom
  config_dir: config
  input_backup_dir: input_backup 

saint_config:
  saint_root: /home/juan95/research/discovery_grant/volumetric_drilling
  drill_size: 4
  marker_namespace: /atracsys/drill_marker
